// src/components/NotificationCenter.tsx
import React from 'react';
import { useAppStore } from '../stores/appStore';

const NotificationCenter: React.FC = () => {
  const {
    globalNotifications,
    isShowingGlobalNotificationCenter,
    toggleNotificationCenter,
    markNotificationAsRead,
    clearAllNotifications,
  } = useAppStore();

  const unreadCount = globalNotifications.filter(n => !n.read).length;

  const getNotificationIcon = (type: string, channel?: number) => {
    switch (type) {
      case 'pairing':
        return (
          <svg className="w-5 h-5 text-blue-400" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clipRule="evenodd" />
          </svg>
        );
      case 'player':
        return (
          <svg className="w-5 h-5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
          </svg>
        );
      case 'alarm':
        return (
          <svg className="w-5 h-5 text-red-400" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
          </svg>
        );
      case 'team':
        return (
          <svg className="w-5 h-5 text-purple-400" fill="currentColor" viewBox="0 0 20 20">
            <path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3z" />
          </svg>
        );
      case 'entity':
        return (
          <svg className="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zm0 4a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1V8zm8 0a1 1 0 011-1h4a1 1 0 011 1v2a1 1 0 01-1 1h-4a1 1 0 01-1-1V8z" clipRule="evenodd" />
          </svg>
        );
      default:
        return (
          <svg className="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
          </svg>
        );
    }
  };

  const formatTimestamp = (timestamp: Date) => {
    const now = new Date();
    const diff = now.getTime() - timestamp.getTime();
    const minutes = Math.floor(diff / 60000);
    const hours = Math.floor(diff / 3600000);
    const days = Math.floor(diff / 86400000);

    if (minutes < 1) return 'Just now';
    if (minutes < 60) return `${minutes}m ago`;
    if (hours < 24) return `${hours}h ago`;
    return `${days}d ago`;
  };

  return (
    <>
      {/* Notification Bell Button */}
      <button
        onClick={toggleNotificationCenter}
        className="relative p-2 text-gray-400 hover:text-white transition-colors"
      >
        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
        </svg>
        
        {unreadCount > 0 && (
          <span className="absolute -top-1 -right-1 bg-red-500 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center">
            {unreadCount > 9 ? '9+' : unreadCount}
          </span>
        )}
      </button>

      {/* Notification Panel */}
      {isShowingGlobalNotificationCenter && (
        <div className="absolute top-full right-0 mt-2 w-96 bg-gray-800 border border-gray-700 rounded-lg shadow-xl z-50 max-h-96 overflow-hidden">
          <div className="p-4 border-b border-gray-700 flex items-center justify-between">
            <h3 className="text-lg font-semibold text-white">Notifications</h3>
            
            <div className="flex items-center space-x-2">
              {globalNotifications.length > 0 && (
                <button
                  onClick={clearAllNotifications}
                  className="text-xs text-gray-400 hover:text-white transition-colors"
                >
                  Clear All
                </button>
              )}
              
              <button
                onClick={toggleNotificationCenter}
                className="text-gray-400 hover:text-white transition-colors"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>

          <div className="max-h-80 overflow-y-auto">
            {globalNotifications.length === 0 ? (
              <div className="p-8 text-center text-gray-400">
                <svg className="w-12 h-12 mx-auto mb-4 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                </svg>
                <p className="text-sm">No notifications</p>
                <p className="text-xs mt-1">You're all caught up!</p>
              </div>
            ) : (
              <div className="divide-y divide-gray-700">
                {globalNotifications.map((notification) => (
                  <div
                    key={notification.id}
                    onClick={() => markNotificationAsRead(notification.id)}
                    className={`p-4 cursor-pointer hover:bg-gray-700 transition-colors ${
                      !notification.read ? 'bg-gray-750' : ''
                    }`}
                  >
                    <div className="flex items-start space-x-3">
                      <div className="flex-shrink-0 mt-1">
                        {getNotificationIcon(notification.type, notification.channel)}
                      </div>
                      
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between mb-1">
                          <h4 className="text-sm font-medium text-white truncate">
                            {notification.title}
                          </h4>
                          
                          <div className="flex items-center space-x-2">
                            <span className="text-xs text-gray-400">
                              {formatTimestamp(notification.timestamp)}
                            </span>
                            
                            {!notification.read && (
                              <div className="w-2 h-2 bg-blue-500 rounded-full" />
                            )}
                          </div>
                        </div>
                        
                        <p className="text-sm text-gray-300 line-clamp-2">
                          {notification.message}
                        </p>
                        
                        {notification.channel && (
                          <div className="mt-2">
                            <span className="inline-flex items-center px-2 py-1 rounded-full text-xs bg-gray-600 text-gray-200">
                              Channel {notification.channel}
                            </span>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
};

export default NotificationCenter;

// src/components/NotificationCenter.vue
<template>
  <div class="notification-center">
    <button 
      @click="toggleNotifications" 
      class="notification-button"
      :class="{ 'has-unread': hasUnreadNotifications }"
    >
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        <path d="M13.73 21a2 2 0 0 1-3.46 0" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
      <span v-if="unreadCount > 0" class="notification-badge">{{ unreadCount }}</span>
    </button>

    <div v-if="showNotifications" class="notification-panel">
      <div class="notification-header">
        <h3>Notifications</h3>
        <button @click="clearAllNotifications" class="clear-button">Clear All</button>
      </div>
      
      <div class="notification-list" ref="notificationList">
        <div 
          v-for="notification in notifications" 
          :key="notification.id"
          class="notification-item"
          :class="{ 'unread': !notification.read }"
          @click="markAsRead(notification.id)"
        >
          <div class="notification-icon" :class="getNotificationIconClass(notification)">
            <!-- Pairing notification icon -->
            <svg v-if="notification.channel === 1001 || notification.type === 'pairing'" width="16" height="16" viewBox="0 0 24 24" fill="none">
              <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <!-- Player logged in icon -->
            <svg v-else-if="notification.channel === 1002 || notification.type === 'player_login'" width="16" height="16" viewBox="0 0 24 24" fill="none">
              <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" stroke="currentColor" stroke-width="2"/>
              <circle cx="12" cy="7" r="4" stroke="currentColor" stroke-width="2"/>
            </svg>
            <!-- Player died icon -->
            <svg v-else-if="notification.channel === 1003 || notification.type === 'player_death'" width="16" height="16" viewBox="0 0 24 24" fill="none">
              <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" stroke="currentColor" stroke-width="2"/>
              <path d="M9 9h6v6H9z" fill="currentColor"/>
            </svg>
            <!-- Smart alarm icon -->
            <svg v-else-if="notification.channel === 1004 || notification.type === 'smart_alarm'" width="16" height="16" viewBox="0 0 24 24" fill="none">
              <path d="M6 6h12v12H6z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              <path d="M9 1v6M15 1v6M1 9h22M1 15h22" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <!-- Team message icon -->
            <svg v-else-if="notification.type === 'team_message'" width="16" height="16" viewBox="0 0 24 24" fill="none">
              <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" stroke="currentColor" stroke-width="2"/>
            </svg>
            <!-- Team changed icon -->
            <svg v-else-if="notification.type === 'team_changed'" width="16" height="16" viewBox="0 0 24 24" fill="none">
              <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" stroke="currentColor" stroke-width="2"/>
              <circle cx="9" cy="7" r="4" stroke="currentColor" stroke-width="2"/>
              <path d="M23 21v-2a4 4 0 0 0-3-3.87" stroke="currentColor" stroke-width="2"/>
              <path d="M16 3.13a4 4 0 0 1 0 7.75" stroke="currentColor" stroke-width="2"/>
            </svg>
            <!-- Entity changed icon -->
            <svg v-else-if="notification.type === 'entity_changed'" width="16" height="16" viewBox="0 0 24 24" fill="none">
              <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" stroke="currentColor" stroke-width="2"/>
            </svg>
            <!-- Default notification icon -->
            <svg v-else width="16" height="16" viewBox="0 0 24 24" fill="none">
              <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2"/>
              <line x1="12" y1="8" x2="12" y2="12" stroke="currentColor" stroke-width="2"/>
              <line x1="12" y1="16" x2="12.01" y2="16" stroke="currentColor" stroke-width="2"/>
            </svg>
          </div>
          
          <div class="notification-content">
            <div class="notification-title">{{ notification.title }}</div>
            <div class="notification-message">{{ notification.message }}</div>
            <div v-if="notification.entityName" class="notification-entity">
              Entity: {{ notification.entityName }} ({{ notification.entityType }})
            </div>
            <div v-if="notification.playerName" class="notification-player">
              Player: {{ notification.playerName }}
            </div>
            <div class="notification-time">{{ formatTime(notification.timestamp) }}</div>
          </div>
        </div>
        
        <div v-if="notifications.length === 0" class="no-notifications">
          No notifications yet
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'NotificationCenter',
  props: {
    notifications: {
      type: Array,
      default: () => []
    }
  },
  data() {
    return {
      showNotifications: false
    }
  },
  computed: {
    unreadCount() {
      return this.notifications.filter(n => !n.read).length;
    },
    hasUnreadNotifications() {
      return this.unreadCount > 0;
    }
  },
  methods: {
    toggleNotifications() {
      this.showNotifications = !this.showNotifications;
    },
    markAsRead(notificationId) {
      this.$emit('mark-as-read', notificationId);
    },
    clearAllNotifications() {
      this.$emit('clear-all');
      this.showNotifications = false;
    },
    getNotificationIconClass(notification) {
      const channelClasses = {
        1001: 'pairing-notification',
        1002: 'login-notification', 
        1003: 'death-notification',
        1004: 'alarm-notification'
      };
      
      const typeClasses = {
        'pairing': 'pairing-notification',
        'player_login': 'login-notification',
        'player_death': 'death-notification', 
        'smart_alarm': 'alarm-notification',
        'team_message': 'team-notification',
        'team_changed': 'team-notification',
        'entity_changed': 'entity-notification'
      };
      
      return channelClasses[notification.channel] || typeClasses[notification.type] || 'default-notification';
    },
    formatTime(timestamp) {
      const now = new Date();
      const notificationTime = new Date(timestamp);
      const diffInMinutes = Math.floor((now - notificationTime) / (1000 * 60));
      
      if (diffInMinutes < 1) {
        return 'Just now';
      } else if (diffInMinutes < 60) {
        return `${diffInMinutes}m ago`;
      } else if (diffInMinutes < 1440) {
        const hours = Math.floor(diffInMinutes / 60);
        return `${hours}h ago`;
      } else {
        const days = Math.floor(diffInMinutes / 1440);
        return `${days}d ago`;
      }
    }
  },
  watch: {
    notifications: {
      handler() {
        // Auto-scroll to top when new notifications arrive
        this.$nextTick(() => {
          if (this.$refs.notificationList) {
            this.$refs.notificationList.scrollTop = 0;
          }
        });
      },
      deep: true
    }
  }
}
</script>

<style scoped>
.notification-center {
  position: relative;
  display: inline-block;
}

.notification-button {
  position: relative;
  background: #2d3748;
  border: 1px solid #4a5568;
  border-radius: 8px;
  padding: 8px 12px;
  color: #e2e8f0;
  cursor: pointer;
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  gap: 8px;
}

.notification-button:hover {
  background: #4a5568;
  border-color: #718096;
}

.notification-button.has-unread {
  border-color: #f56565;
  box-shadow: 0 0 0 1px rgba(245, 101, 101, 0.3);
}

.notification-badge {
  background: #f56565;
  color: white;
  border-radius: 50%;
  padding: 2px 6px;
  font-size: 12px;
  font-weight: bold;
  min-width: 18px;
  text-align: center;
  line-height: 1;
}

.notification-panel {
  position: absolute;
  top: 100%;
  right: 0;
  margin-top: 8px;
  width: 350px;
  max-height: 500px;
  background: #2d3748;
  border: 1px solid #4a5568;
  border-radius: 8px;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.3);
  z-index: 1000;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.notification-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px;
  border-bottom: 1px solid #4a5568;
  background: #1a202c;
}

.notification-header h3 {
  margin: 0;
  color: #e2e8f0;
  font-size: 16px;
  font-weight: 600;
}

.clear-button {
  background: none;
  border: none;
  color: #f56565;
  cursor: pointer;
  font-size: 14px;
  padding: 4px 8px;
  border-radius: 4px;
  transition: background-color 0.2s ease;
}

.clear-button:hover {
  background: rgba(245, 101, 101, 0.1);
}

.notification-list {
  flex: 1;
  overflow-y: auto;
  min-height: 0;
}

.notification-item {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  padding: 12px 16px;
  border-bottom: 1px solid #4a5568;
  cursor: pointer;
  transition: background-color 0.2s ease;
}

.notification-item:hover {
  background: #374151;
}

.notification-item.unread {
  background: rgba(59, 130, 246, 0.1);
  border-left: 3px solid #3b82f6;
}

.notification-item:last-child {
  border-bottom: none;
}

.notification-icon {
  flex-shrink: 0;
  width: 32px;
  height: 32px;
  background: #4a5568;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #e2e8f0;
}

/* Notification type specific icon colors */
.notification-icon.pairing-notification {
  background: #f59e0b;
  color: #1f2937;
}

.notification-icon.login-notification {
  background: #10b981;
  color: #1f2937;
}

.notification-icon.death-notification {
  background: #ef4444;
  color: #ffffff;
}

.notification-icon.alarm-notification {
  background: #f59e0b;
  color: #1f2937;
}

.notification-icon.team-notification {
  background: #3b82f6;
  color: #ffffff;
}

.notification-icon.entity-notification {
  background: #8b5cf6;
  color: #ffffff;
}

.notification-icon.default-notification {
  background: #6b7280;
  color: #e2e8f0;
}

.notification-content {
  flex: 1;
  min-width: 0;
}

.notification-title {
  font-weight: 600;
  color: #e2e8f0;
  font-size: 14px;
  margin-bottom: 4px;
}

.notification-message {
  color: #a0aec0;
  font-size: 13px;
  line-height: 1.4;
  margin-bottom: 4px;
  word-wrap: break-word;
}

.notification-entity,
.notification-player {
  color: #9ca3af;
  font-size: 12px;
  font-style: italic;
  margin-bottom: 2px;
}

.notification-time {
  color: #718096;
  font-size: 12px;
}

.no-notifications {
  padding: 32px 16px;
  text-align: center;
  color: #718096;
  font-style: italic;
}

/* Scrollbar styling */
.notification-list::-webkit-scrollbar {
  width: 6px;
}

.notification-list::-webkit-scrollbar-track {
  background: #2d3748;
}

.notification-list::-webkit-scrollbar-thumb {
  background: #4a5568;
  border-radius: 3px;
}

.notification-list::-webkit-scrollbar-thumb:hover {
  background: #718096;
}
</style>
